sudo: false
language: php
php:
  - 7.1
  - 7.0

env:
  global:
    - THEME_DIR=./site/web/app/themes/sage/

before_install:
  - phpenv config-rm xdebug.ini
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install -g gulp bower

install: 
  - cd $THEME_DIR
  - composer install --no-dev --no-scripts --quiet --optimize-autoloader
  - npm install --devDependencies --silent --no-spin
  - bower install
  - gulp --production

script:
  - cd $TRAVIS_BUILD_DIR
